# Generated by Django 2.0.2 on 2019-03-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_desc', models.CharField(max_length=500)),
                ('start_date', models.DateTimeField(verbose_name='Date of Event')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
