# Generated by Django 2.0.2 on 2019-03-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xrhome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_title',
            new_name='title',
        ),
    ]
